# Generated by Django 2.2.1 on 2019-06-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_text', models.CharField(blank=True, max_length=50, verbose_name='Movie')),
            ],
            options={
                'verbose_name': '네이버 영화명',
            },
        ),
        migrations.CreateModel(
            name='Url_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.CharField(blank=True, max_length=200, verbose_name='URL')),
            ],
            options={
                'verbose_name': '옥션 상품 URL',
            },
        ),
    ]
