# Generated by Django 2.2.1 on 2019-06-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_data',
            fields=[
                ('movie_text', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='Movie')),
            ],
            options={
                'verbose_name_plural': '네이버 영화명',
            },
        ),
        migrations.CreateModel(
            name='Url_data',
            fields=[
                ('url_text', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': '옥션 상품 URL',
            },
        ),
    ]
